local_backend: true

backend:
  name: git-gateway

media_folder: "src/stories/assets" # Media files will be stored in the repo under public/
public_folder: "src/stories/assets" # The src attribute for uploaded media will begin with /

collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/docs
    label: "Docs" # Used in the UI
    folder: "src/stories" # The path to the folder where the mdx documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    slug: "{{title}}" # Filename template, e.g., title.stories.mdx
    format: yaml-frontmatter
    frontmatter_delimiter: ["{/** ---", "--- **/}"]
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
